set -e
sudo docker build -t test_image_spyros .
sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/train_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierRotAugRotSelfsupervision"
#sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierRotAugRotSelfsupervision --num_novel=5 --num_train=1 --num_episodes=2000"
#sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/train_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierRotAugRotSelfsupervision_SemisupervisedTieredUnlabeled"
#sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierRotAugRotSelfsupervision_SemisupervisedTieredUnlabeled --num_novel=5 --num_train=1 --num_episodes=2000"
#sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierRotAugRotSelfsupervision_SemisupervisedTieredUnlabeled --num_novel=5 --num_train=5 --num_episodes=2000"
#sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/train_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierLocSelfsupervision"
#sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierLocSelfsupervision --num_novel=5 --num_train=1 --num_episodes=2000"
#sudo docker run --gpus "device=2" -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot.py --config=miniImageNet/WRNd28w10CosineClassifierLocSelfsupervision --num_novel=5 --num_train=5 --num_episodes=2000"

#sudo docker run --gpus "device=2" -v /mnt/data/workspace/sgidaris/all_datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/train_fewshot.py --config=cifar/WRNd28w10CosineClassifierRotAugRotSelfsupervision"
#sudo docker run --gpus "device=2" -v /mnt/data/workspace/sgidaris/all_datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot.py --config=cifar/WRNd28w10CosineClassifierRotAugRotSelfsupervision --num_novel=5 --num_train=1 --num_episodes=5000"
#sudo docker run --gpus "device=2" -v /mnt/data/workspace/sgidaris/all_datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot.py --config=cifar/WRNd28w10CosineClassifierRotAugRotSelfsupervision --num_novel=5 --num_train=5 --num_episodes=5000"

#sudo docker run --gpus "device=2" --ipc=host -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/train_fewshot.py --config=ImageNet/ResNet10CosineClassifierRotSelfsupervision --num_workers=8"
#sudo docker run --gpus "device=2" --ipc=host -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/save_features_imagenet.py --config=ImageNet/ResNet10CosineClassifierRotSelfsupervision --split='val'"
#sudo docker run --gpus "device=2" --ipc=host -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot_imagenet.py --config=ImageNet/ResNet10CosineClassifierRotSelfsupervision_eval --testset --num_train=1 --bias_novel=0.8"
#sudo docker run --gpus "device=2" --ipc=host -v /media/data/datasets:/BF3S/datasets -v /media/data/local_storage/sgidaris/spyros/experiments/BF3S:/BF3S/experiments test_image_spyros bash -c "python scripts/test_fewshot_imagenet.py --config=ImageNet/ResNet10CosineClassifierRotSelfsupervision_eval --testset --num_train=20 --bias_novel=0.6"
